version: "3"

services:
  app:
    build: .
    container_name: netflix_linebot
    environment:
      LINE_ACCESS_TOKEN: ${LINE_ACCESS_TOKEN}
      LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET}
    ports:
      - "30678:8000"